baseURL = "http://example.org/"
languageCode = "en-us"
title = "Watch This Space Improv"
theme = "quadra"

rssLimit = 15

[params]
  title       = "Watch This Space Improv!"
  subtitle    = "Follow the fun!"
  cover       = ""
  description = ""
  metaDescription = ""

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 0

[[menu.main]]
  name = "Venues"
  url = "/Venues"
  weight = 1
